metrics:
  hosts:
    metrics-01.devnet.shimmer.iota.cafe:

supports:
  hosts:
    analysisentry-01.devnet.shimmer.iota.cafe:
      entryNodeSeed: "{{ ANALYSISSENTRY_01_ENTRYNODE_SEED }}"
      manaDashboardHost: "http://dashboards.nectar.iota.cafe:80"
      logLevel: "debug"

goshimmers:
  children:
    internal_nodes:
      hosts:
        bootstrap-01.devnet.shimmer.iota.cafe:
          seed: "{{ BOOTSTRAP_01_SEED }}"
          bootstrap: true
        vanilla-01.devnet.shimmer.iota.cafe:
          seed: "{{ VANILLA_01_SEED }}"
        node-01.devnet.shimmer.iota.cafe:
          seed: "{{ NODE_01_SEED }}"
        node-02.devnet.shimmer.iota.cafe:
          seed: "{{ NODE_02_SEED }}"
        node-03.devnet.shimmer.iota.cafe:
          seed: "{{ NODE_03_SEED }}"
        node-04.devnet.shimmer.iota.cafe:
          seed: "{{ NODE_04_SEED }}"
        node-05.devnet.shimmer.iota.cafe:
          seed: "{{ NODE_05_SEED }}"
        faucet-01.devnet.shimmer.iota.cafe:
          seed: "{{ FAUCET_01_SEED }}"
          faucet: true
          faucetSeed: "{{ FAUCET_01_FAUCET_SEED }}"
    public_nodes:
      hosts:
        public-node-01.devnet.shimmer.iota.cafe:
        public-node-02.devnet.shimmer.iota.cafe:
        public-node-03.devnet.shimmer.iota.cafe:

  vars:
    entryNodeHost: "analysisentry-01.devnet.shimmer.iota.cafe"
    entryNodePubKey: "2PV5487xMw5rasGBXXWeqSi4hLz7r19YBt8Y1TGAsQbj"
    bootstrapNodePubKey: "Gm7W191NDnqyF7KJycZqK7V6ENLwqxTwoKQN4SmpkB24"
    remoteLoggerHost: "metrics-01.devnet.shimmer.iota.cafe"
    communityEntryNode: "5EDH4uY78EA6wrBkHHAVBWBMDt7EcksRq6pjzipoW15B@entry-0.devnet.tanglebay.com:14646,CAB87iQZR6BjBrCgEBupQJ4gpEBgvGKKv3uuGVRBKb4n@entry-1.devnet.tanglebay.com:14646"
    logLevel: "debug"
    remoteLogs: true

asset_registries:
  hosts:
    asset-registry-01.devnet.shimmer.iota.cafe:

lbs:
  hosts:
    lb.devnet.shimmer.iota.cafe:
