name: Manually Triggered Docker Image

on: workflow_dispatch

jobs:

  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      -   name: Checkout repository
          uses: actions/checkout@v3

      -   name: Publish to Docker Hub
          uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c
          with:
            repository: iotafoundationtesting/goshimmer
            username: '${{ secrets.IOTAFOUNDATIONTESTING_HUB_DOCKER_LOGIN }}'
            password: '${{ secrets.IOTAFOUNDATIONTESTING_HUB_DOCKER_PASSWORD }}'
            tags: testing
